.PHONY: clean All

All:
	@echo "----------Building project:[ SEC-4-Challenge - Debug ]----------"
	@cd "SEC-4-Challenge" && "$(MAKE)" -f  "SEC-4-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ SEC-4-Challenge - Debug ]----------"
	@cd "SEC-4-Challenge" && "$(MAKE)" -f  "SEC-4-Challenge.mk" clean
